apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operator-database-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Build Labs Database Catalog
  publisher: IBM Build Labs
  sourceType: grpc
  image: DATABASE_CATALOG_IMAGE
  updateStrategy:
    registryPoll:
      interval: 10m