# permissions for end users to view databaseclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasecluster-viewer-role
rules:
- apiGroups:
  - database.sample.third.party
  resources:
  - databaseclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.sample.third.party
  resources:
  - databaseclusters/status
  verbs:
  - get
