# permissions for end users to view databasebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasebackup-viewer-role
rules:
- apiGroups:
  - database.sample.third.party
  resources:
  - databasebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.sample.third.party
  resources:
  - databasebackups/status
  verbs:
  - get
