apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operator-application-catalog
  namespace: openshift-operators
spec:
  displayName: IBM Build Labs Apps Catalog
  publisher: IBM Build Labs
  sourceType: grpc
  image: APPLICATION_CATALOG_IMAGE
  updateStrategy:
    registryPoll:
      interval: 10m