apiVersion: v1
kind: Service
metadata:
  name: prometheus-instance
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-instance