apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-role
  namespace: database
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: database-rolebinding
  namespace: database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: database-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: database