apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup
  namespace: database
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: database-backup
            image: docker.io/nheidloff/operator-database-backup:v1.0.4
            imagePullPolicy: IfNotPresent
            env:
            - name: BACKUP_RESOURCE_NAME
              value: "databasebackup-manual"
            - name: CLOUD_OBJECT_STORAGE_API_KEY
              value: "xxx"
            - name: NAMESPACE
              value: "database"
            - name: CLOUD_OBJECT_STORAGE_SERVICE_INSTANCE_ID
              value: "xxx"
            - name: CLOUD_OBJECT_STORAGE_SERVICE_ENDPOINT
              value: "https://s3.fra.eu.cloud-object-storage.appdomain.cloud"
          restartPolicy: OnFailure            
  backoffLimit: 0