apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-backup-role
  namespace: database
rules:
- apiGroups:
  - "database.sample.third.party"
  resources:
  - databasebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: database-backup-rolebinding
  namespace: database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: database-backup-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: database