apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "application.sample.ibm.com/v1alpha1",
          "kind": "Application",
          "metadata": {
            "name": "application",
            "namespace": "application-alpha"
          },
          "spec": {
            "amountPods": 1,
            "databaseName": "database",
            "databaseNamespace": "database",
            "version": "1.0.0"
          }
        },
        {
          "apiVersion": "application.sample.ibm.com/v1beta1",
          "kind": "Application",
          "metadata": {
            "name": "application",
            "namespace": "application-beta"
          },
          "spec": {
            "amountPods": 1,
            "databaseName": "database",
            "databaseNamespace": "database",
            "title": "movies",
            "version": "1.0.0"
          }
        }
      ]
    capabilities: Auto Pilot
    support: sample.ibm.com
    createdAt: 2022-05-22 19:40Z
    repository: https://github.com/IBM/operator-sample-go
    containerImage: hub.docker.com
    operators.operatorframework.io/builder: operator-sdk-v1.18.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: operator-application.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: Application
      description: Application is the Schema for the Application API
      kind: Application
      name: applications.application.sample.ibm.com
      version: v1alpha1
    - displayName: Application
      description: Application is the Schema for the Application API
      kind: Application
      name: applications.application.sample.ibm.com
      version: v1beta1
  description: IBM Build Labs Application Operator
  displayName: Application Operator
  description: |-
    # IBM Build Labs Application Operator

    ## Introduction

    The IBM Build Labs operators provide Day 1 and Day 2 capabilities for a sample two tier 
    application.  
    
    This application operator relates to the front end microservice which provides a simple 
    web UI.  The web server provides a single HTTP enpoint:
    
    >**/hello** - Renders a Hello greeting to the names persisted in the corresponding database.
    
    ## Day 1 capabilities create the following resources:

    * Deployment, Pods, Service
    * Database (a Custom Resource reconciled by another operator which creates the schema)

    ## Day 2 capabilities:

    * Auto scaling pods according to how many times the /hello endpoint is invoked
    

    ## Note
    This sample is based on an [Operator Reference Architecture](https://github.com/IBM/operator-sample-go) from IBM Build Labs.
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAADEAAAAtCAYAAAAHiIP8AAAACXBIWXMAAAsSAAALEgHS3X78AAANm0lEQVRogc2ZeXTV1bXHP+c33PnmJiEhDAkFAiJCMEFEolIiiq2gBRFLW/vesmvJa3mtdXiuV+urvtVX29XB+p666pCnthatpYNoK6EgBJGhUQoyzxpICDEJGe/4G8/744ZAuDeQiH+8vdZd99712/uc/d3D2fvsn5BSSj5jkraN292DG40iDQMkCI+OEgqhRHIQXu9nup/2WSwiXRentQ1j+w6SW+tI7T+E23oaaRi4lg2A0FQUrxeRm4Pv8svwVc7EN+tqtJJihHZpaohL8YR0XaxDh+l55XckNm3DamtnsMsJIVDDQYLXXUP4q0vwzpqJUFUQYsh6fCoQUkrsxpN0P/0c0dXv4BjmkDc+lxRNJTR7FpH7luMpm4oYIpAhg5CWRaJmLe0/fwqzuXVIm12M9LwIucv+mfDdX0fx+QYtNyQQ0jTpeupZul5+7ZKtP6BCqkLuHbeR+/C/oeZGBiczWBAylaLzp0/SsWIlDBK2ct5/VwKDiBQhBDk3zmbYEz9ByQlfnH8wIKTj0PXkM3S88ArSdS/Iq0Vy8JVNxpxSzg5nDLs6whRGVKrGG4yONWDv2kNi526stvaLISH39vnk/9ej2KZF1+4D+EcXEZ4wbuggpJQk1qyj9cEf4JgDh5Cen0vO0tsx593Ku+1F/PkDg+MtNrbjIoBIUGNOmY/FszxM1Nsx171D929/j3GyOet6LmBqXszZ19NxvJlkYxOjZpZRXv0L1EBgaCDs5maal34Do7E5eygIQfjzlRjLH6CmdRR/3Z6kpdNGSomUaSMIQd+J4/WozJrkZcn1fqbndhH75VP0/OVvuI6DoqrIvFxa2mN0SRVTKnhw8eKgSxdFVZj4k+8z/MuL+p1gF6wy0nXprv5N2lpZAAhVpXPuQlZWLqf2DeiK95yPj+/eFuFP2+Kc6nAQgGE6bNqbYOvBFJOLPXxlycNcOXEyvo4WArfMQxQX0/Hvj6O/u42gtFAEKIqC/3NjyJt9DaEpl2foMSAIKSVW/XGib9VkZxDwwbh5vBS4m84d9kAslI7S8GmZFrBtl73HUxxsVBg/Yj73Lw4xc5IHIQRlj97PgYYT2D0x8j8/i4IF8whWlKFFckCIjDpyQU/E3/grdldP1metwy/j+dJ7iNl6X5U+s7iUEq8uGD9CJz9HZcpYDz1Jl7YeByEEAkiLSCzb5UiTQfUaQXmpB4+TQmuoZ3xxHv77foCnouKixW9gTyQSxNe8k/WZ4vex6dplxMwgUkquu8JHwCtYvytJyKdw5+wQS64PMixHQVPhsbsipMwIdQdTvLwuxoFGk5F5GgsrA7y4NorXShHZv5fYY3Vo723A+aQVF4ksmwzl5RdtRQYEYX30McaJk9lBTLuSA4XlyKZ0GH3S6bB8QQ6TSjyUj9MpL/UgRNrajV0pQl6NPL/G3HIf0yd6+cN7caaM0dmyP8XYWAPf3/Vjirs/Rro21jn7mLXv4lm2DBG5cNE7vx4B6XBI7diVtZkTioJRdTMN7RJBOoQ+arZ5/PUuvjjdT8UET99pdKglxsSfb2XZyn1pWSHIDQr+5ZYwtbtTrNyc4BNvITEthOJm5pV9ohF5svGCAAYEgZQ4h49lFwj4OF5URsI8F6CkotTD8DwlHfO97n/pgyZmjgqztbGbwy3xPiAA86b70FRIKD42FM9DZDGYmzJwjxz9lCAAqyV7c6cXFlDflGTGiXVcc3J9LwSYN92Pqp6N3dMxk7cOtvGfN5cydXiQlbs+6efZqWM9FA/TkAj25JVheIKZm0mJc/Ro+juRJFF/Auk4gwThujixOGc0lICDoAudw6e6KXr2e9yy5wVG9xxPA1MFY4u0vlIipWTtoTa8imD2+Dy+XjGSX+84heWcOcUg4BUUF6gAdOoROvyFmRiA6J4DnPjVi+z8yj3sv/dh3JSRwTdgYgsp0cIh9GlT+HjXUdrjJkjwpkwipNClS57ZhetKNFWgq/3lX6hrQgIPvHmIrpRNQ4/BmgNtLJxW1AfEpwscKUkJD12eHEaQri2motHtKnQIjcS2fcit+0BAuPRzZ87mQYBQFPIe+Ff00nG4Pj/1d36T8LGP0Un3Qbbq5WRkLK3jr+KRpRGGhTUKImdR7DsVZU9LjEeqxhLxpbfoTNq8uL2JBVMK0VQFKeGfbgwxt9zPtj1ROvYVsrnkZlpn3sTVjW/T/sGHffqqSHxI8nwaip6pclYQQlHwXVeZ/m3ZDCsZTufx4/jHjqFh0hxeiVXQFCzBF/AQPWRyqDHO1ZO8PPq1CIqAl7c3MXtsLg9WjUVT0xF7+fAgt72ymyOtca4YGWZfvcVDL3YwZriGYcKmKQ8SVwNMDEimtK0AJF4pCeMSQKIBocJ80PVBegLo7d7gVBMFER/FK54hOL2c/C7BS892YbebRJOSjXtSCAHrdiaYf7WfqWM1ugyHb19b0gcA4PrSfG65LJ+DLXFKC0K8sCZKe9SlPZrujIUWRFUENxQ0E2xqJF/a6PSvc97ScQglM437d7G9irvNzTh/r8N8uwZzx4dgW+SsfA112jSklHxw2OTh33TTE7f7iY7KV/nFPXlMKtb7da5nyHUlKVPy9FtR/rg1nnG5+tI1AZafWkHP8y9mKKroGkW//BHBW+dnPuu3SUMDyfsfpGfREnq+9x8k39uCE4/jGCbW2nW9bbXg6ss8fPdLITzaWXEh4FSHw33Pd7C/wcKw0kqnW3KJaUksG378+27+uDWekZ8zJvr59swYRs2aDCUB1GF5eKZOyfqsfzi5LsamzdjRWAaj8XYNnru+hhg1CkURLJzlp7HNYcWGGK48e3RKIJmSfOPJ04zMV8gPqRiWpL7F5qZyPwGvwHVBOcdJJYUeHlsaQKmuxjjRlLXtD8yoQBs1MiuIfp4QxcXoM6ZnZbROnsKo/t++66miCJZ9McgXrjpbpKSEqjIfu+tNDp+0eHePwRt/T7B6e5IDDRZv1cW5sdyP55zjeFiOzg/vCpO79W90/e7PWQEoXg/hJQuzJnUmCE3D8+U7sre+UpL8wxvY69YiHQezvYNYbS13sZGy4l6HCli9PcnL62Ig0p5J91fpT0Obw8O/7sTqvaZ7dIWHFgWYeGwzpx9/AtfILGQAwVkz8My4asCWPON6Kg2D2J1LMfYezLCKC6QKCklUzqZ9xx6Sp1oQmor4wu08E1hKQ2LwM1ZVEXxrno/FJ9+g67mXs4YwgBYJM+L5/8Y7c8bgQSAl9nubiS6/FzeVQgn6kSUlNB5ppNNVMQFBb/Aj0YGgkMiCYlaN/yr7iisxPIEB7wAC8DgGN7t7uL1+JcaOXekkz3b9VQTDvrOMyL3fSo84B6CsgwJp21jPPodUVfSbbkSOHs3hx37KqbfWIl0XDfDjEkTiRZ5NUkXFGlGMdm0l/sqZqGNKUMKh9JrJJE7DSVI7d2Ft3oLeUI+0rfO37kfBWVcx/FdPoublXpBv0MMzq6OTjx56DPPdzXilRM1u6LMLkx7nq34fCIGTMpApY0Crn0/+yRMoev5/0EpKLso7pDGm29ND+yM/pGdtLdK58BDtU5MQBK+poPBnP0IrKR6cyJBmsVIik0miL/2WzpdWYPdkT8ZPS4rfR2TxAnIfuBc1P2/Qcp9utO84mP/YSccTT5PYvR9pZ15UhkJCVfBdNp6873wT/003IAaoBwPKX9JLlmSK5IZaulesJLn3AG5qaJNyRdfwXT6R8J0LCS68FSV88eFxNrokEJAOMUwT6+BhEhs3kXz/H9iNp7A6u5G23Xt3Tlc9qarokTDa6JH4Z1Tgr5qN58oyhN8/5BcrFwXhui62baPr+kUXd10XIUS6yTNNvIqC29WF3dqG2dKKjCfQNA3h96EMG4ZaWICSl4shJX6/v58xHMdBO+f93fl6uK5LIpEgEAignNOSZzTnhmGwYsUKVq1axe7du9mxYwdHjhzpxyOl5P3338cwDF577TVs26a5uZnXX38d4fGgDh9OU8DPq0cOsSYZ42BRAf4b5uCdNhVt5Ahipkl1dXWGMaqrq0kkEgCYpsmrr77Km2++yYcffgjA+vXrWb9+PeZ50/kMEB6PB8uy0HWdQCCAruscPHiw36TCsix27tyJoij09PSgaRqhUAjfOa+oIpEIRUVFLF68mG3btvUpBxAKhQicN55vamrCsizq6uqQUqKqKo7joKoqfr8fx3HYt28fCxYs6LdPVhBn3Hb69GlisRhXXHEF0WiU+vr6PiAnTpxg6tSpaJqGz+dDCIGiKP1CQdM0VFVF13VycnKwrLPV+Xxe13XZuHEjkydPpq6ujkQi0Rei7e3txONxFEVh8uTJ7Ny583yVs49s/H4/c+fO5dixY2iaxh133MGGDRuora1l+/btHDp0iMrKyj7lz5Cu63254TgOrusSjUZJJpOEQqE+Pikleu8xapomx48fJxwOU1FRwZw5c6ipqUH25kxVVRX19fUAVFVVcfRo5jAt447t9A6n2traWLx4cR+ou+++m7179+L3+5k/fz5qb0M2bty4PsVs22b16tXk5+czYcIEOjs72bJlC0uXLu3jh3Q4BoNBampqUBQFKSXz5s0jHA5TUFBAbW0t8Xgc13Vpb29n0aJFxONxVq1aRVlZWQaIz+SIvZTjcSjkum4/z5+hSwbx/4H+DynQNfIBRsx8AAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - application.sample.ibm.com
          resources:
          - applications
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - application.sample.ibm.com
          resources:
          - applications/finalizers
          verbs:
          - update
        - apiGroups:
          - application.sample.ibm.com
          resources:
          - applications/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - application.sample.ibm.com
          resources:
          - applications/metadata
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - database.sample.third.party
          resources:
          - databases
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: operator-application-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: operator-application-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/diwakarptiwari/application-operator:v1.0.4
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: operator-application-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: operator-application-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - go
  - kubernetes
  - golang
  - devops
  - automation
  - operator
  - k8s
  - kubernetes-operator
  - day2
  links:
  - name: Operator Application
    url: https://github.com/ibm/operator-sample-go
  maturity: alpha
  provider:
    name: IBM Build Labs
    url: https://github.com/ibm/operator-sample-go
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1alpha1
    - v1beta1
    containerPort: 443
    conversionCRDs:
    - applications.application.sample.ibm.com
    deploymentName: operator-application-controller-manager
    generateName: capplications.kb.io
    sideEffects: None
    targetPort: 9443
    type: ConversionWebhook
    webhookPath: /convert
  - admissionReviewVersions:
    - v1alpha1
    - v1beta1
    containerPort: 443
    deploymentName: operator-application-controller-manager
    failurePolicy: Fail
    generateName: mapplication.kb.io
    rules:
    - apiGroups:
      - application.sample.ibm.com
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - applications
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-application-sample-ibm-com-v1beta1-application
  - admissionReviewVersions:
    - v1alpha1
    - v1beta1
    containerPort: 443
    deploymentName: operator-application-controller-manager
    failurePolicy: Fail
    generateName: vapplication.kb.io
    rules:
    - apiGroups:
      - application.sample.ibm.com
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - applications
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-application-sample-ibm-com-v1beta1-application