apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operator-database-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Build Labs Database Catalog
  publisher: IBM Build Labs
  sourceType: grpc
  image: quay.io/tsuedbroecker/database-operator-catalog:v1.0.36
  updateStrategy:
    registryPoll:
      interval: 10m