apiVersion: batch/v1
kind: CronJob
metadata:
  name: application-scaler
  namespace: application-beta
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: application-scale
              image: docker.io/deleeuw/operator-application-scaler:v1.0.23
              imagePullPolicy: IfNotPresent
              env:
              - name: APPLICATION_RESOURCE_NAME
                value: "application"
              - name: APPLICATION_RESOURCE_NAMESPACE
                value: "application-beta"
          restartPolicy: OnFailure 
