apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: database.sample.third.party/v1alpha1
kind: DatabaseCluster
metadata:
  name: databasecluster-sample
  namespace: database
spec:
  image: quay.io/diwakarptiwari/database-service:v1.0.4
  amountPods: 2
