apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: database.sample.third.party/v1alpha1
kind: DatabaseCluster
metadata:
  name: databasecluster-sample
  namespace: database
spec:
  image: docker.io/nheidloff/database-service:v1.0.117
  amountPods: 2
