apiVersion: database.sample.third.party/v1alpha1
kind: DatabaseBackup
metadata:
  name: test-databasebackup-manual
  namespace: test-database
spec:
  image: DATABASE_BACKUP_IMAGE
  repos:
  - name: ibmcos-repo
    type: ibmcos
    secretName: ibmcos-repo
    serviceEndpoint: s3.eu.cloud-object-storage.appdomain.cloud
    cosRegion: eu-geo
    bucketNamePrefix: "database-backup-"
  manualTrigger:
    time: "2022-04-20T02:59:43.1Z"
    repo: ibmcos-repo
  scheduledTrigger:
    schedule: "*/3 * * * *"
    repo: ibmcos-repo
