apiVersion: v1
kind: Namespace
metadata:
  name: test-database
---
apiVersion: database.sample.third.party/v1alpha1
kind: DatabaseCluster
metadata:
  name: test-databasecluster-sample
  namespace: test-database
spec:
  image: DATABASE_SERVICE_IMAGE
  amountPods: 2
