apiVersion: database.sample.third.party/v1alpha1
kind: DatabaseBackup
metadata:
  name: test-databasebackup-manual
  namespace: test-database
spec:
  image: DATABASE_BACKUP_IMAGE
  repos:
  - name: ibmcos-repo #not relevant to change and not used
    type: ibmcos #not relevant to change and not used
    secretName: test-ibmcos-repo # important and will be used to define the access
    serviceEndpoint: s3.eu.cloud-object-storage.appdomain.cloud #not relevant to change
    cosRegion: eu-geo #not relevant to change??
    bucketNamePrefix: "test-database-backup-" # important and will be used
  manualTrigger:
    time: "2022-04-20T02:59:43.1Z" #not relevant to change and not used
    repo: ibmcos-repo #not relevant to change and not used
  scheduledTrigger:
    schedule: "*/3 * * * *" # important and will be used to define schedule
    repo: ibmcos-repo #not relevant to change and not used
