apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator-database.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: Database
      kind: Database
      name: databases.database.sample.third.party
      version: v1alpha1
  description: database-operator
  displayName: database-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sample
  - database-operator
  links:
  - name: Operator Database
    url: https://operator-database.domain
  maturity: alpha
  provider:
    name: database.sample.third.party
    url: https://github.com/ibm/operator-sample-go
  version: 0.0.0
